[package]
name = "rocks"
version = "0.1.0"
authors = ["Michael Li <alimy@gility.net>"]

[[bin]]
name = "guessing_game"
path = "src/bin/guessing_game.rs"

[[bin]]
name = "hello_world"
path = "src/bin/hello_world.rs"

[workspace]
members = [
    "guessing_game",
]

[dependencies]
guessing_game = { path = "guessing_game" }