[package]
name = "rocks"
version = "0.1.0"
authors = ["Michael Li <alimy@gility.net>"]

[workspace]
members = [
    "guessing_game",
    "rocks_ctl",
]

[dependencies]
guessing_game = { path = "guessing_game" }
clap = "2"